#pragma once

namespace H {
	#ifndef EXTENSION_COMPONENTS_LIST_H
	#define EXTENSION_COMPONENTS_LIST_H

	#define EXTENSION_COMPONENTS_LIST

	#endif

	#ifndef EXTENSION_HANDLERS_LIST_H
	#define EXTENSION_HANDLERS_LIST_H

	#define EXTENSION_HANDLERS_LIST

	#endif

	#ifndef EXTENSION_GROUPS_LIST_H
	#define EXTENSION_GROUPS_LIST_H

	#define EXTENSION_GROUPS_LIST

	#endif

	#ifndef EXTENSION_SYSTEMS_LIST_H
	#define EXTENSION_SYSTEMS_LIST_H

	#define EXTENSION_SYSTEMS_LIST
	#endif

	#ifndef EXTENSION_MESSAGES_LIST_H
	#define EXTENSION_MESSAGES_LIST_H

	#define EXTENSION_MESSAGES_LIST

	#endif

	#ifndef EXPORTS_MESSAGE_MACROS_H
	#define EXPORTS_MESSAGE_MACROS_H

	#define	EXPORTS_MESSAGES

	#endif
}